# Pre-commit
# @see http://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: end-of-file-fixer

  - repo: https://github.com/AppleBoiy/Kotlin.git
    rev: 2ae4287bc8367dfe82c8d785b59af6751166c3df
    hooks:
      - id: mvn-verify # it does not accept arguments
      - id: mvn-compile
      - id: mvn-test # it does not accept arguments
#      - id: test
      - id: pull
