# Pre-commit
# @see http://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: end-of-file-fixer

  - repo: https://github.com/AppleBoiy/Kotlin.git
    rev: 6b51b09d738b6fe4de8025606ab95ee3499aa9e0
    hooks:
      - id: mvn-verify # it does not accept arguments
      - id: mvn-compile
      - id: mvn-test # it does not accept arguments
      - id: pull
