# Pre-commit
# @see http://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: end-of-file-fixer

  - repo: https://github.com/AppleBoiy/Kotlin.git
    rev: dfb107fb742b3b1a766556ddffbc0fec4a41ba79
    hooks:
      - id: mvn-verify # it does not accept arguments
      - id: mvn-compile
      - id: mvn-test # it does not accept arguments
